fix compilation error
Summary:
Fix compilation errors casuing contbuild tests failing, likely due to recent update of clang warning flags somewhere (e.g., https://fb.workplace.com/groups/fbcode/permalink/7177745785595532/)

example error: https://www.internalfb.com/sandcastle/workflow/445856363111781820

Reviewed By: minsii

Differential Revision: D53928762

fbshipit-source-id: 23987241bc0dc82a0791ca32b3e1d29b492afc53